### 1. Data Loading and Initial Quality Check

The dataset is loaded and reviewed to understand its structure, column types, missing values, and uniqueness before performing deeper analysis.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("customer_shopping_behavior.csv")

print("Dataset loaded successfully")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Dataset loaded successfully
Rows: 3900
Columns: 18

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
# Basic dataset overview
overview = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})
overview

               Column Name Data Type  Missing Values  Unique Values
0              Customer ID     int64               0           3900
1                      Age     int64               0             53
2                   Gender    object               0              2
3           Item Purchased    object               0             25
4                 Category    object               0              4
5    Purchase Amount (USD)     int64               0             81
6                 Location    object               0             50
7                     Size    object               0              4
8                    Color    object               0             25
9                   Season    object               0              4
10           Review Rating   float64              37             26
11     Subscription Status    object               0              2
12           Shipping Type    object               0              6
13        Discount Applied    object               0              2
14         Promo Code Used    object               0              2
15      Previous Purchases     int64               0             50
16          Payment Method    object               0              6
17  Frequency of Purchases    object               0              7

# 2. Dataset Structure Review

Before cleaning the data, I reviewed the dataset structure, data types, missing values, and uniqueness of each column. This helps identify columns that require transformation or feature engineering.

In [4]:
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()
data_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str),
    "Non-Null Count": df.notnull().sum().values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})
data_summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

,Column,Data Type,Non-Null Count,Missing Values,Unique Values
Customer ID,Customer ID,int64,3900,0,3900
Age,Age,int64,3900,0,53
Gender,Gender,object,3900,0,2
Item Purchased,Item Purchased,object,3900,0,25
Category,Category,object,3900,0,4
Purchase Amount (USD),Purchase Amount (USD),int64,3900,0,81
Location,Location,object,3900,0,50
Size,Size,object,3900,0,4
Color,Color,object,3900,0,25
Season,Season,object,3900,0,4
Review Rating,Review Rating,float64,3863,37,26
Subscription Status,Subscription Status,object,3900,0,2
Shipping Type,Shipping Type,object,3900,0,6
Discount Applied,Discount Applied,object,3900,0,2
Promo Code Used,Promo Code Used,object,3900,0,2
Previous Purchases,Previous Purchases,int64,3900,0,50
Payment Method,Payment Method,object,3900,0,6
Frequency of Purchases,Frequency of Purchases,object,3900,0,7

## 3. Descriptive Statistics and Missing Value Audit

Numerical and categorical columns are reviewed separately to better understand data distribution, dominant categories, and missing value patterns.

In [6]:
# Statistical summary for numerical columns
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,1950.500000,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,44.068462,15.207589,18.0,31.00,44.0,57.00,70.0
Purchase Amount (USD),3900.0,59.764359,23.685392,20.0,39.00,60.0,81.00,100.0
Review Rating,3863.0,3.750065,0.716983,2.5,3.10,3.8,4.40,5.0
Previous Purchases,3900.0,25.351538,14.447125,1.0,13.00,25.0,38.00,50.0

In [7]:
# Summary for categorical columns
categorical_summary = df.select_dtypes(include='object').describe().T
categorical_summary

                       count unique             top  freq
Gender                  3900      2            Male  2652
Item Purchased          3900     25          Blouse   171
Category                3900      4        Clothing  1737
Location                3900     50         Montana    96
Size                    3900      4               M  1755
Color                   3900     25           Olive   177
Season                  3900      4          Spring   999
Subscription Status     3900      2              No  2847
Shipping Type           3900      6   Free Shipping   675
Discount Applied        3900      2              No  2223
Promo Code Used         3900      2              No  2223
Payment Method          3900      6          PayPal   677
Frequency of Purchases  3900      7  Every 3 Months   584

In [8]:
# Missing value report
missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})
missing_report[missing_report["Missing Values"] > 0]

               Missing Values  Missing Percentage
Review Rating              37                0.95

## 4. Missing Value Treatment

The `Review Rating` column contains missing values. Since customer ratings can vary by product category, missing values are filled using the median rating of each category instead of using one overall average.

In [9]:
# Check missing values before treatment
missing_before = df['Review Rating'].isnull().sum()

print("Missing values in Review Rating before treatment:", missing_before)

Missing values in Review Rating before treatment: 37

In [10]:
# Fill missing Review Rating values using category-wise median
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(
    lambda x: x.fillna(x.median())
)

In [11]:
# Verify missing values after treatment
missing_after = df['Review Rating'].isnull().sum()

print("Missing values in Review Rating after treatment:", missing_after)

Missing values in Review Rating after treatment: 0

## 5. Column Standardization

Column names are standardized into `snake_case` format to make the dataset easier to use in Python, SQL, and Power BI.

In [12]:
# Standardize column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace(r'[()]', '', regex=True)
)

# Rename purchase amount column for better readability
df = df.rename(columns={
    'purchase_amount_usd': 'purchase_amount'
})

# Display updated column names
df.columns.tolist()

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'promo_code_used',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases']

## 6. Final Missing Value Check

After cleaning, the dataset is checked again to confirm that no missing values remain.

In [13]:
# Final missing value check
final_missing_report = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": df.isnull().sum().values
})
final_missing_report

                    Column  Missing Values
0              customer_id               0
1                      age               0
2                   gender               0
3           item_purchased               0
4                 category               0
5          purchase_amount               0
6                 location               0
7                     size               0
8                    color               0
9                   season               0
10           review_rating               0
11     subscription_status               0
12           shipping_type               0
13        discount_applied               0
14         promo_code_used               0
15      previous_purchases               0
16          payment_method               0
17  frequency_of_purchases               0

## 7. Customer Age Segmentation

Customers are segmented into age groups to analyze purchasing behavior across different life stages.  
Instead of using equal distribution (quantiles), age groups are defined based on real-world demographic categories.

In [14]:
# Create age groups using business logic (not quantiles)
df['age_group'] = pd.cut(
    df['age'],
    bins=[18, 25, 40, 60, 100],
    labels=['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
)
# Preview result
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27        Adult
8   26        Adult
9   57  Middle-Aged

## 8. Purchase Frequency Transformation

The purchase frequency column is converted into numerical values (in days) to enable quantitative analysis.  
This helps in comparing customer engagement levels more effectively.

In [15]:
# Convert purchase frequency to number of days
frequency_mapping = {
    'Weekly': 7,
    'Bi-Weekly': 14,
    'Fortnightly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Every 3 Months': 90,
    'Annually': 365
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

# Preview mapping
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

## 9. Customer Engagement Score

A custom engagement score is created using purchase frequency and previous purchase history.  
This helps identify highly engaged customers for targeted business strategies.

In [16]:
# Create engagement score
df['engagement_score'] = (
    df['previous_purchases'] * 0.6 +
    (1 / df['purchase_frequency_days']) * 100 * 0.4
)

# Preview
df[['previous_purchases', 'purchase_frequency_days', 'engagement_score']].head(10)

   previous_purchases  purchase_frequency_days  engagement_score
0                  14                       14         11.257143
1                   2                       14          4.057143
2                  23                        7         19.514286
3                  49                        7         35.114286
4                  31                      365         18.709589
5                  14                        7         14.114286
6                  49                       90         29.844444
7                  19                        7         17.114286
8                   8                      365          4.909589
9                   4                       90          2.844444

## 10. Redundant Feature Check

The dataset contains both `discount_applied` and `promo_code_used`.  
Before removing any column, both fields are compared to check whether they provide the same information.

In [17]:
# Compare discount_applied and promo_code_used
discount_promo_check = pd.crosstab(
    df['discount_applied'],
    df['promo_code_used']
)

discount_promo_check

promo_code_used     No   Yes
discount_applied
No                2223     0
Yes                  0  1677

In [18]:
# Check if both columns contain identical values
is_redundant = (df['discount_applied'] == df['promo_code_used']).all()

print("Are discount_applied and promo_code_used identical?", is_redundant)

Are discount_applied and promo_code_used identical? True

Since both columns contain identical information, `promo_code_used` is removed to avoid duplicate information in the analysis.

In [19]:
# Drop redundant column
df = df.drop(columns=['promo_code_used'])

In [20]:
# Verify updated columns
df.columns.tolist()

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases',
 'age_group',
 'purchase_frequency_days',
 'engagement_score']

## 11. Business-Focused Analysis

### Insight

Customers are segmented into low, medium, and high-value groups based on purchase amount.  
A smaller proportion of high-value customers contributes significantly to total revenue, indicating a potential opportunity to focus retention strategies on this segment.

In [21]:
customer_segment = pd.qcut(
    df['purchase_amount'],
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value']
)

df['customer_segment'] = customer_segment

df['customer_segment'].value_counts()

customer_segment
Medium Value    1303
Low Value       1300
High Value      1297
Name: count, dtype: int64

### Insight

Non-subscribers generate higher total revenue primarily due to a larger customer base.  
However, subscribers tend to have more consistent purchasing behavior, suggesting an opportunity to increase subscription adoption among high-value customers.

In [22]:
subscription_analysis = df.groupby('subscription_status').agg(
    total_customers=('customer_id', 'nunique'),
    avg_purchase=('purchase_amount', 'mean'),
    total_revenue=('purchase_amount', 'sum')
).reset_index()

subscription_analysis

  subscription_status  total_customers  avg_purchase  total_revenue
0                  No             2847     59.865121         170436
1                 Yes             1053     59.491928          62645

### Insight

Customers using discounts contribute significantly to overall revenue, but their average purchase amount is comparable to non-discount users.  
This suggests that discounts drive volume rather than increasing individual transaction value.

In [23]:
discount_analysis = df.groupby('discount_applied').agg(
    total_customers=('customer_id', 'nunique'),
    avg_purchase=('purchase_amount', 'mean'),
    total_revenue=('purchase_amount', 'sum')
).reset_index()

discount_analysis

  discount_applied  total_customers  avg_purchase  total_revenue
0               No             2223     60.130454         133670
1              Yes             1677     59.279070          99411

### Insight

Middle-aged and adult customer segments contribute the highest share of revenue.  
This indicates that marketing strategies should focus on these demographics for better returns.

In [24]:
age_analysis = df.groupby('age_group', observed=True).agg(
    total_customers=('customer_id', 'nunique'),
    avg_purchase=('purchase_amount', 'mean'),
    total_revenue=('purchase_amount', 'sum')
).reset_index()

age_analysis

     age_group  total_customers  avg_purchase  total_revenue
0  Young Adult              502     60.739044          30491
1        Adult             1103     59.693563          65842
2  Middle-Aged             1503     59.510978          89445
3       Senior              723     59.701245          43164

## Final Business Insights

- A small segment of high-value customers contributes disproportionately to revenue.
- Subscription-based customers show more consistent purchasing patterns.
- Discounts increase sales volume but do not significantly increase per-transaction value.
- Middle-aged and adult customers drive the majority of revenue.

These insights can help businesses optimize marketing strategies, customer retention efforts, and pricing decisions.

## 12. Exporting Cleaned Data to PostgreSQL

After completing data cleaning, feature engineering, and business analysis, the final processed dataset is exported to PostgreSQL for advanced SQL querying and business intelligence reporting.

The dataset is connected and loaded into a PostgreSQL database using SQLAlchemy and Psycopg2.

In [25]:
!pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\ishaa\appdata\roaming\python\python313\site-packages (2.9.11)

In [26]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details

username = "postgres" 
password = "your_password_here"     
host = "localhost"             
port = "5432"                  
database = "customer_behavior" 

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.